export default [
  {
    chainId: 1,
    name: 'Ethereum Mainnet',
    rpc: 'https://cloudflare-eth.com',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    explorer: 'https://etherscan.io',
  },
  {
    chainId: 2,
    name: 'Expanse Network',
    rpc: 'https://node.expanse.tech',
    nativeCurrency: {
      name: 'Expanse Network Ether',
      symbol: 'EXP',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 3,
    name: 'Ethereum Testnet Ropsten',
    rpc: 'https://ropsten.infura.io/v3/${INFURA_API_KEY}',
    nativeCurrency: {
      name: 'Ropsten Ether',
      symbol: 'ROP',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 4,
    name: 'Ethereum Testnet Rinkeby',
    rpc: 'https://rinkeby.infura.io/v3/${INFURA_API_KEY}',
    nativeCurrency: {
      name: 'Rinkeby Ether',
      symbol: 'RIN',
      decimals: 18,
    },
    explorer: 'https://rinkeby.etherscan.io',
  },
  {
    chainId: 5,
    name: 'Ethereum Testnet Görli',
    rpc: 'https://rpc.goerli.mudit.blog/',
    nativeCurrency: {
      name: 'Görli Ether',
      symbol: 'GOR',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 6,
    name: 'Ethereum Classic Testnet Kotti',
    nativeCurrency: {
      name: 'Kotti Ether',
      symbol: 'KOT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 7,
    name: 'ThaiChain',
    rpc: 'https://rpc.dome.cloud',
    nativeCurrency: {
      name: 'ThaiChain Ether',
      symbol: 'TCH',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 10,
    name: 'Optimistic Ethereum',
    rpc: 'https://mainnet.optimism.io/',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'OETH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 11,
    name: 'Metadium Mainnet',
    rpc: 'https://api.metadium.com/prod',
    nativeCurrency: {
      name: 'Metadium Mainnet Ether',
      symbol: 'META',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 12,
    name: 'Metadium Testnet',
    rpc: 'https://api.metadium.com/dev',
    nativeCurrency: {
      name: 'Metadium Testnet Ether',
      symbol: 'KAL',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 30,
    name: 'RSK Mainnet',
    rpc: 'https://public-node.rsk.co',
    nativeCurrency: {
      name: 'RSK Mainnet Ether',
      symbol: 'RBTC',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 42,
    name: 'Ethereum Testnet Kovan',
    rpc: 'https://kovan.poa.network',
    nativeCurrency: {
      name: 'Kovan Ether',
      symbol: 'KOV',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 44,
    name: 'Darwinia Crab Network',
    nativeCurrency: {
      name: 'Crab Token',
      symbol: 'CRING',
      decimals: 9,
    },
    explorer: '',
  },
  {
    chainId: 50,
    name: 'XinFin Network Mainnet',
    rpc: 'https://rpc.xinfin.network',
    nativeCurrency: {
      name: 'XinFin',
      symbol: 'XDC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 52,
    name: 'CoinEx Smart Chain Mainnet',
    rpc: 'https://rpc-mainnet.coinex.net',
    nativeCurrency: {
      name: 'CoinEx Chain Native Token',
      symbol: 'cet',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 56,
    name: 'Binance Smart Chain Mainnet',
    rpc: 'https://bsc-dataseed1.binance.org',
    nativeCurrency: {
      name: 'Binance Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
    explorer: 'https://bscscan.com',
  },
  {
    chainId: 57,
    name: 'Syscoin Mainnet',
    rpc: 'https://rpc.syscoin.org',
    nativeCurrency: {
      name: 'Syscoin',
      symbol: 'SYS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 58,
    name: 'Ontology Mainnet',
    rpc: 'https://dappnode1.ont.io:20339',
    nativeCurrency: {
      name: 'ONG',
      symbol: 'ONG',
      decimals: 9,
    },
    explorer: 'https://explorer.ont.io/',
  },
  {
    chainId: 59,
    name: 'EOS Mainnet',
    rpc: 'https://api.eosargentina.io',
    nativeCurrency: {
      name: 'EOS',
      symbol: 'EOS',
      decimals: 18,
    },
    explorer: 'https://bloks.eosargentina.io',
  },
  {
    chainId: 60,
    name: 'GoChain',
    rpc: 'https://rpc.gochain.io',
    nativeCurrency: {
      name: 'GoChain Ether',
      symbol: 'GO',
      decimals: 18,
    },
    explorer: 'https://explorer.gochain.io',
  },
  {
    chainId: 61,
    name: 'Ethereum Classic Mainnet',
    rpc: 'https://ethereumclassic.network',
    nativeCurrency: {
      name: 'Ethereum Classic Ether',
      symbol: 'ETC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 62,
    name: 'Ethereum Classic Testnet Morden',
    nativeCurrency: {
      name: 'Ethereum Classic Testnet Ether',
      symbol: 'TETC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 63,
    name: 'Ethereum Classic Testnet Mordor',
    nativeCurrency: {
      name: 'Mordor Classic Testnet Ether',
      symbol: 'METC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 64,
    name: 'Ellaism',
    rpc: 'https://jsonrpc.ellaism.org',
    nativeCurrency: {
      name: 'Ellaism Ether',
      symbol: 'ELLA',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 65,
    name: 'OKExChain Testnet',
    rpc: 'https://exchaintestrpc.okex.org',
    nativeCurrency: {
      name: 'OKExChain Global Utility Token in testnet',
      symbol: 'OKT',
      decimals: 18,
    },
    explorer: 'https://www.oklink.com/okexchain-test',
  },
  {
    chainId: 66,
    name: 'OKExChain Mainnet',
    rpc: 'https://exchainrpc.okex.org',
    nativeCurrency: {
      name: 'OKExChain Global Utility Token',
      symbol: 'OKT',
      decimals: 18,
    },
    explorer: 'https://www.oklink.com/okexchain',
  },

  {
    chainId: 68,
    name: 'SoterOne Mainnet',
    rpc: 'https://rpc.soter.one',
    nativeCurrency: {
      name: 'SoterOne Mainnet Ether',
      symbol: 'SOTER',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 69,
    name: 'Optimistic Ethereum Testnet Kovan',
    rpc: 'https://kovan.optimism.io/',
    nativeCurrency: {
      name: 'Kovan Ether',
      symbol: 'KOR',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 76,
    name: 'Mix',
    rpc: 'https://rpc2.mix-blockchain.org:8647',
    nativeCurrency: {
      name: 'Mix Ether',
      symbol: 'MIX',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 77,
    name: 'POA Network Sokol',
    rpc: 'https://sokol.poa.network',
    nativeCurrency: {
      name: 'POA Sokol Ether',
      symbol: 'POA',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 78,
    name: 'PrimusChain mainnet',
    rpc: 'https://ethnode.primusmoney.com/mainnet',
    nativeCurrency: {
      name: 'Primus Ether',
      symbol: 'PETH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 80,
    name: 'GeneChain',
    rpc: 'https://rpc.genechain.io',
    nativeCurrency: {
      name: 'RNA',
      symbol: 'RNA',
      decimals: 18,
    },
    explorer: 'https://scan.genechain.io',
  },
  {
    chainId: 82,
    name: 'Meter Mainnet',
    rpc: 'https://rpc.meter.io',
    nativeCurrency: {
      name: 'Meter',
      symbol: 'MTR',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 86,
    name: 'GateChain Mainnet',
    rpc: 'https://evm.gatenode.cc',
    nativeCurrency: {
      name: 'GateToken',
      symbol: 'GT',
      decimals: 18,
    },
    explorer: 'https://www.gatescan.org',
  },
  {
    chainId: 88,
    name: 'TomoChain',
    rpc: 'https://rpc.tomochain.com',
    nativeCurrency: {
      name: 'TomoChain Ether',
      symbol: 'TOMO',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 97,
    name: 'Binance Smart Chain Testnet',
    rpc: 'https://data-seed-prebsc-1-s1.binance.org:8545',
    nativeCurrency: {
      name: 'Binance Chain Native Token',
      symbol: 'tBNB',
      decimals: 18,
    },
    explorer: 'https://testnet.bscscan.com',
  },
  {
    chainId: 99,
    name: 'POA Network Core',
    rpc: 'https://core.poanetwork.dev',
    nativeCurrency: {
      name: 'POA Network Core Ether',
      symbol: 'SKL',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 100,
    name: 'xDAI Chain',
    rpc: 'https://rpc.xdaichain.com',
    nativeCurrency: {
      name: 'xDAI',
      symbol: 'xDAI',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 101,
    name: 'EtherInc',
    rpc: 'https://api.einc.io/jsonrpc/mainnet',
    nativeCurrency: {
      name: 'EtherInc Ether',
      symbol: 'ETI',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 108,
    name: 'ThunderCore Mainnet',
    rpc: 'https://mainnet-rpc.thundercore.com',
    nativeCurrency: {
      name: 'ThunderCore Mainnet Ether',
      symbol: 'TT',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 111,
    name: 'EtherLite Chain',
    rpc: 'https://rpc.etherlite.org',
    nativeCurrency: {
      name: 'EtherLite',
      symbol: 'ETL',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 122,
    name: 'Fuse Mainnet',
    rpc: 'https://rpc.fuse.io',
    nativeCurrency: {
      name: 'Fuse',
      symbol: 'FUSE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 124,
    name: 'Decentralized Web Mainnet',
    rpc: 'https://decentralized-web.tech/dw_rpc.php',
    nativeCurrency: {
      name: 'Decentralized Web Utility',
      symbol: 'DWU',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 127,
    name: 'Factory 127 Mainnet',
    nativeCurrency: {
      name: 'Factory 127 Token',
      symbol: 'FETH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 128,
    name: 'Huobi ECO Chain Mainnet',
    rpc: 'https://http-mainnet.hecochain.com',
    nativeCurrency: {
      name: 'Huobi ECO Chain Native Token',
      symbol: 'HT',
      decimals: 18,
    },
    explorer: 'https://hecoinfo.com',
  },
  {
    chainId: 137,
    name: 'Polygon Mainnet',
    rpc: 'https://polygon-rpc.com',
    nativeCurrency: {
      name: 'Matic',
      symbol: 'MATIC',
      decimals: 18,
    },
    explorer: 'https://polygonscan.com',
  },
  {
    chainId: 142,
    name: 'DAX CHAIN',
    rpc: 'https://rpc.prodax.io',
    nativeCurrency: {
      name: 'Prodax',
      symbol: 'DAX',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 163,
    name: 'Lightstreams Mainnet',
    rpc: 'https://node.mainnet.lightstreams.io',
    nativeCurrency: {
      name: 'Lightstreams PHT',
      symbol: 'PHT',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 200,
    name: 'Arbitrum on xDai',
    rpc: 'https://arbitrum.xdaichain.com/',
    nativeCurrency: {
      name: 'xDAI',
      symbol: 'xDAI',
      decimals: 18,
    },
    explorer: 'https://blockscout.com/xdai/arbitrum',
  },
  {
    chainId: 211,
    name: 'Freight Trust Network',
    rpc: 'http://13.57.207.168:3435',
    nativeCurrency: {
      name: 'Freight Trust Native',
      symbol: '0xF',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 246,
    name: 'Energy Web Chain',
    rpc: 'https://rpc.energyweb.org',
    nativeCurrency: {
      name: 'Energy Web Token',
      symbol: 'EWT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 250,
    name: 'Fantom Opera',
    rpc: 'https://rpc.ftm.tools',
    nativeCurrency: {
      name: 'Fantom',
      symbol: 'FTM',
      decimals: 18,
    },
    explorer: 'https://ftmscan.com',
  },
  {
    chainId: 256,
    name: 'Huobi ECO Chain Testnet',
    rpc: 'https://http-testnet.hecochain.com',
    nativeCurrency: {
      name: 'Huobi ECO Chain Test Native Token',
      symbol: 'htt',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 269,
    name: 'High Performance Blockchain',
    rpc: 'https://hpbnode.com',
    nativeCurrency: {
      name: 'High Performance Blockchain Ether',
      symbol: 'HPB',
      decimals: 18,
    },
    explorer: 'https://hpbscan.org/',
  },
  {
    chainId: 321,
    name: 'KCC Mainnet',
    rpc: 'https://rpc-mainnet.kcc.network',
    nativeCurrency: {
      name: 'KuCoin Token',
      symbol: 'KCS',
      decimals: 18,
    },
    explorer: 'https://explorer.kcc.io/en',
  },
  {
    chainId: 322,
    name: 'KCC Testnet',
    rpc: 'https://rpc-testnet.kcc.network',
    nativeCurrency: {
      name: 'KuCoin Testnet Token',
      symbol: 'tKCS',
      decimals: 18,
    },
    explorer: 'https://scan-testnet.kcc.network',
  },
  {
    chainId: 361,
    name: 'Theta Mainnet',
    rpc: 'https://eth-rpc-api.thetatoken.org/rpc',
    nativeCurrency: {
      name: 'Theta Fuel',
      symbol: 'TFUEL',
      decimals: 18,
    },
    explorer: 'https://explorer.thetatoken.org',
  },
  {
    chainId: 363,
    name: 'Theta Sapphire Testnet',
    rpc: 'https://eth-rpc-api-sapphire.thetatoken.org/rpc',
    nativeCurrency: {
      name: 'Theta Fuel',
      symbol: 'TFUEL',
      decimals: 18,
    },
    explorer: 'https://guardian-testnet-sapphire-explorer.thetatoken.org',
  },
  {
    chainId: 364,
    name: 'Theta Amber Testnet',
    rpc: 'https://eth-rpc-api-amber.thetatoken.org/rpc',
    nativeCurrency: {
      name: 'Theta Fuel',
      symbol: 'TFUEL',
      decimals: 18,
    },
    explorer: 'https://guardian-testnet-amber-explorer.thetatoken.org',
  },
  {
    chainId: 365,
    name: 'Theta Testnet',
    rpc: 'https://eth-rpc-api-testnet.thetatoken.org/rpc',
    nativeCurrency: {
      name: 'Theta Fuel',
      symbol: 'TFUEL',
      decimals: 18,
    },
    explorer: 'https://testnet-explorer.thetatoken.org',
  },
  {
    chainId: 369,
    name: 'PulseChain Mainnet',
    rpc: 'https://rpc.mainnet.pulsechain.com/v1/${PULSECHAIN_API_KEY}',
    nativeCurrency: {
      name: 'Pulse',
      symbol: 'PLS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 385,
    name: 'Lisinski',
    rpc: 'https://rpc-bitfalls1.lisinski.online',
    nativeCurrency: {
      name: 'Lisinski Ether',
      symbol: 'LISINSKI',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 420,
    name: 'Optimistic Ethereum Testnet Goerli',
    rpc: 'https://goerli.optimism.io/',
    nativeCurrency: {
      name: 'Görli Ether',
      symbol: 'GOR',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 499,
    name: 'Rupaya',
    nativeCurrency: {
      name: 'Rupaya',
      symbol: 'RUPX',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 558,
    name: 'Tao Network',
    rpc: 'https://rpc.testnet.tao.network',
    nativeCurrency: {
      name: 'Tao',
      symbol: 'TAO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 595,
    name: 'Acala Mandala Testnet',
    nativeCurrency: {
      name: 'Acala Mandala Token',
      symbol: 'mACA',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 686,
    name: 'Karura Network',
    nativeCurrency: {
      name: 'Karura Token',
      symbol: 'KAR',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 787,
    name: 'Acala Network',
    nativeCurrency: {
      name: 'Acala Token',
      symbol: 'ACA',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 803,
    name: 'Haic',
    rpc: 'https://orig.haichain.io/',
    nativeCurrency: {
      name: 'Haicoin',
      symbol: 'HAIC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 820,
    name: 'Callisto Mainnet',
    rpc: 'https://clo-geth.0xinfra.com',
    nativeCurrency: {
      name: 'Callisto Mainnet Ether',
      symbol: 'CLO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 821,
    name: 'Callisto Testnet',
    nativeCurrency: {
      name: 'Callisto Testnet Ether',
      symbol: 'TCLO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 888,
    name: 'Wanchain',
    rpc: 'https://gwan-ssl.wandevs.org:56891/',
    nativeCurrency: {
      name: 'Wancoin',
      symbol: 'WAN',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 940,
    name: 'PulseChain Testnet',
    rpc: 'https://rpc.testnet.pulsechain.com/v1/${PULSECHAIN_API_KEY}',
    nativeCurrency: {
      name: 'Test Pulse',
      symbol: 'tPLS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 977,
    name: 'Nepal Blockchain Network',
    rpc: 'https://api.nepalblockchain.dev',
    nativeCurrency: {
      name: 'Nepal Blockchain Network Ether',
      symbol: 'YETI',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 999,
    name: 'Wanchain Testnet',
    rpc: 'https://gwan-ssl.wandevs.org:46891/',
    nativeCurrency: {
      name: 'Wancoin',
      symbol: 'WAN',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1001,
    name: 'Klaytn Testnet Baobab',
    rpc: 'https://node-api.klaytnapi.com/v1/klaytn',
    nativeCurrency: {
      name: 'KLAY',
      symbol: 'KLAY',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1007,
    name: 'Newton Testnet',
    rpc: 'https://rpc1.newchain.newtonproject.org',
    nativeCurrency: {
      name: 'Newton',
      symbol: 'NEW',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1010,
    name: 'Evrice Network',
    rpc: 'https://meta.evrice.com',
    nativeCurrency: {
      name: 'Evrice',
      symbol: 'EVC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1012,
    name: 'Newton',
    rpc: 'https://global.rpc.mainnet.newtonproject.org',
    nativeCurrency: {
      name: 'Newton',
      symbol: 'NEW',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1022,
    name: 'Sakura',
    nativeCurrency: {
      name: 'Sakura',
      symbol: 'SKU',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1023,
    name: 'Clover Testnet',
    nativeCurrency: {
      name: 'Clover',
      symbol: 'CLV',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1024,
    name: 'Clover Mainnet',
    rpc: 'https://rpc-ivy.clover.finance',
    nativeCurrency: {
      name: 'Clover',
      symbol: 'CLV',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1139,
    name: 'MathChain',
    rpc: 'https://mathchain-asia.maiziqianbao.net/rpc',
    nativeCurrency: {
      name: 'MathChain',
      symbol: 'MATH',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 1285,
    name: 'Moonriver',
    rpc: 'https://rpc.moonriver.moonbeam.network',
    nativeCurrency: {
      name: 'Moonriver',
      symbol: 'MOVR',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1286,
    name: 'Moonrock',
    nativeCurrency: {
      name: 'Rocs',
      symbol: 'ROC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1287,
    name: 'Moonbase Alpha',
    rpc: 'https://rpc.testnet.moonbeam.network',
    nativeCurrency: {
      name: 'Dev',
      symbol: 'DEV',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1288,
    name: 'Moonshadow',
    nativeCurrency: {
      name: 'Moonshadow',
      symbol: 'MSHD',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1618,
    name: 'Catecoin Chain Mainnet',
    rpc: 'https://send.catechain.com',
    nativeCurrency: {
      name: 'Catecoin',
      symbol: 'CATE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1620,
    name: 'Atheios',
    rpc: 'https://wallet.atheios.com:8797',
    nativeCurrency: {
      name: 'Atheios Ether',
      symbol: 'ATH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1856,
    name: 'Teslafunds',
    rpc: 'https://tsfapi.europool.me',
    nativeCurrency: {
      name: 'Teslafunds Ether',
      symbol: 'TSF',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1987,
    name: 'EtherGem',
    rpc: 'https://jsonrpc.egem.io/custom',
    nativeCurrency: {
      name: 'EtherGem Ether',
      symbol: 'EGEM',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 2020,
    name: '420coin',
    nativeCurrency: {
      name: 'Fourtwenty',
      symbol: '420',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 2021,
    name: 'Edgeware Mainnet',
    rpc: 'https://mainnet1.edgewa.re',
    nativeCurrency: {
      name: 'Edge',
      symbol: 'EDG',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 2022,
    name: 'Beresheet Testnet',
    rpc: 'https://beresheet1.edgewa.re',
    nativeCurrency: {
      name: 'Testnet Edge',
      symbol: 'tEDG',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 2559,
    name: 'Kortho Mainnet',
    rpc: 'https://www.kortho-chain.com',
    nativeCurrency: {
      name: 'KorthoChain',
      symbol: 'KTO',
      decimals: 11,
    },
    explorer: '',
  },
  {
    chainId: 4002,
    name: 'Fantom Testnet',
    rpc: 'https://rpc.testnet.fantom.network',
    nativeCurrency: {
      name: 'Fantom',
      symbol: 'FTM',
      decimals: 18,
    },
    explorer: 'https://testnet.ftmscan.com/',
  },
  {
    chainId: 4689,
    name: 'IoTeX Network Mainnet',
    rpc: 'https://babel-api.mainnet.iotex.io',
    nativeCurrency: {
      name: 'IoTeX',
      symbol: 'IOTX',
      decimals: 18,
    },
    explorer: 'https://iotexscan.io',
  },
  {
    chainId: 4690,
    name: 'IoTeX Network Testnet',
    rpc: 'https://babel-api.testnet.iotex.io',
    nativeCurrency: {
      name: 'IoTeX',
      symbol: 'IOTX',
      decimals: 18,
    },
    explorer: 'https://testnet.iotexscan.io',
  },
  {
    chainId: 5197,
    name: 'EraSwap Mainnet',
    rpc: 'https://mainnet.eraswap.network',
    nativeCurrency: {
      name: 'EraSwap',
      symbol: 'ES',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 5700,
    name: 'Syscoin Tanenbaum Testnet',
    rpc: 'https://rpc.tanenbaum.io',
    nativeCurrency: {
      name: 'Testnet Syscoin',
      symbol: 'tSYS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 5851,
    name: 'Ontology Testnet',
    rpc: 'https://polaris1.ont.io:20339',
    nativeCurrency: {
      name: 'ONG',
      symbol: 'ONG',
      decimals: 9,
    },
    explorer: 'https://explorer.ont.io/testnet',
  },
  {
    chainId: 5869,
    name: 'Wegochain Rubidium Mainnet',
    rpc: 'https://proxy.wegochain.io',
    nativeCurrency: {
      name: 'Rubid',
      symbol: 'RBD',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 8029,
    name: 'MDGL Testnet',
    rpc: 'https://testnet.mdgl.io',
    nativeCurrency: {
      name: 'MDGL Token',
      symbol: 'MDGLT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 8080,
    name: 'GeneChain Adenine Testnet',
    rpc: 'https://rpc-testnet.genechain.io',
    nativeCurrency: {
      name: 'Testnet RNA',
      symbol: 'tRNA',
      decimals: 18,
    },
    explorer: 'https://scan-testnet.genechain.io',
  },
  {
    chainId: 8217,
    name: 'Klaytn Mainnet Cypress',
    rpc: 'https://node-api.klaytnapi.com/v1/klaytn',
    nativeCurrency: {
      name: 'KLAY',
      symbol: 'KLAY',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 8285,
    name: 'KorthoTest',
    rpc: 'https://www.krotho-test.net',
    nativeCurrency: {
      name: 'Kortho Test',
      symbol: 'KTO',
      decimals: 11,
    },
    explorer: '',
  },
  {
    chainId: 8723,
    name: 'TOOL Global Mainnet',
    rpc: 'https://mainnet-web3.wolot.io',
    nativeCurrency: {
      name: 'TOOL Global',
      symbol: 'OLO',
      decimals: 18,
    },
    explorer: 'https://www.olo.network',
  },
  {
    chainId: 8724,
    name: 'TOOL Global Testnet',
    rpc: 'https://testnet-web3.wolot.io',
    nativeCurrency: {
      name: 'TOOL Global',
      symbol: 'OLO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 8995,
    name: 'bloxberg',
    rpc: 'https://core.bloxberg.org',
    nativeCurrency: {
      name: 'BERG',
      symbol: 'U+25B3',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 10000,
    name: 'Smart Bitcoin Cash',
    rpc: 'https://smartbch.greyh.at',
    nativeCurrency: {
      name: 'Bitcoin Cash',
      symbol: 'BCH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 10001,
    name: 'Smart Bitcoin Cash Testnet',
    rpc: 'https://rpc-testnet.smartbch.org',
    nativeCurrency: {
      name: 'Bitcoin Cash Test Token',
      symbol: 'BCHT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 10101,
    name: 'Blockchain Genesis Mainnet',
    rpc: 'https://eu.mainnet.xixoio.com',
    nativeCurrency: {
      name: 'GEN',
      symbol: 'GEN',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 16000,
    name: 'MetaDot Mainnet',
    rpc: 'https://mainnet.metadot.network',
    nativeCurrency: {
      name: 'MetaDot Token',
      symbol: 'MTT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 16001,
    name: 'MetaDot Testnet',
    rpc: 'https://testnet.metadot.network',
    nativeCurrency: {
      name: 'MetaDot Token TestNet',
      symbol: 'MTT-test',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 24484,
    name: 'Webchain',
    rpc: 'https://node1.webchain.network',
    nativeCurrency: {
      name: 'Webchain Ether',
      symbol: 'WEB',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 24734,
    name: 'MintMe.com Coin',
    rpc: 'https://node1.mintme.com',
    nativeCurrency: {
      name: 'MintMe.com Coin',
      symbol: 'MINTME',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 31102,
    name: 'Ethersocial Network',
    rpc: 'https://api.esn.gonspool.com',
    nativeCurrency: {
      name: 'Ethersocial Network Ether',
      symbol: 'ESN',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 31337,
    name: 'GoChain Testnet',
    rpc: 'https://testnet-rpc.gochain.io',
    nativeCurrency: {
      name: 'GoChain Coin',
      symbol: 'GO',
      decimals: 18,
    },
    explorer: 'https://testnet-explorer.gochain.io',
  },
  {
    chainId: 32659,
    name: 'Fusion Mainnet',
    rpc: 'https://mainnet.anyswap.exchange',
    nativeCurrency: {
      name: 'Fusion',
      symbol: 'FSN',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 39797,
    name: 'Energi Mainnet',
    rpc: 'https://nodeapi.gen3.energi.network',
    nativeCurrency: {
      name: 'Energi',
      symbol: 'NRG',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 42069,
    name: 'pegglecoin',
    nativeCurrency: {
      name: 'pegglecoin',
      symbol: 'peggle',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 42161,
    name: 'Arbitrum One',
    rpc: 'https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'AETH',
      decimals: 18,
    },
    explorer: 'https://arbiscan.io',
  },
  {
    chainId: 42220,
    name: 'Celo Mainnet',
    rpc: 'https://forno.celo.org',
    nativeCurrency: {
      name: 'CELO',
      symbol: 'CELO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 43110,
    name: 'Athereum',
    rpc: 'https://ava.network:21015/ext/evm/rpc',
    nativeCurrency: {
      name: 'Athereum Ether',
      symbol: 'ATH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 43113,
    name: 'Avalanche Fuji Testnet',
    rpc: 'https://api.avax-test.network/ext/bc/C/rpc',
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 43114,
    name: 'Avalanche Mainnet',
    rpc: 'https://api.avax.network/ext/bc/C/rpc',
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 44787,
    name: 'Celo Alfajores Testnet',
    rpc: 'https://alfajores-forno.celo-testnet.org',
    nativeCurrency: {
      name: 'CELO',
      symbol: 'CELO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 49797,
    name: 'Energi Testnet',
    rpc: 'https://nodeapi.test3.energi.network',
    nativeCurrency: {
      name: 'Energi',
      symbol: 'tNRG',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 62320,
    name: 'Celo Baklava Testnet',
    rpc: 'https://baklava-forno.celo-testnet.org',
    nativeCurrency: {
      name: 'CELO',
      symbol: 'CELO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 71393,
    name: 'Polyjuice Testnet',
    rpc: 'https://godwoken-testnet-web3-rpc.ckbapp.dev',
    nativeCurrency: {
      name: 'CKB',
      symbol: 'CKB',
      decimals: 8,
    },
    explorer: '',
  },
  {
    chainId: 73799,
    name: 'Energy Web Volta Testnet',
    rpc: 'https://volta-rpc.energyweb.org',
    nativeCurrency: {
      name: 'Volta Token',
      symbol: 'VT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 78110,
    name: 'Firenze test network',
    rpc: 'https://ethnode.primusmoney.com/firenze',
    nativeCurrency: {
      name: 'Firenze Ether',
      symbol: 'FIN',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 80001,
    name: 'Matic(Polygon) Testnet Mumbai',
    rpc: 'https://rpc-mumbai.matic.today',
    nativeCurrency: {
      name: 'Matic',
      symbol: 'tMATIC',
      decimals: 18,
    },
    explorer: 'https://mumbai.polygonscan.com/',
  },
  {
    chainId: 100000,
    name: 'QuarkChain Mainnet Root',
    rpc: 'http://jrpc.mainnet.quarkchain.io:38391/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 100001,
    name: 'QuarkChain Mainnet Shard 0',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39000/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/0',
  },
  {
    chainId: 100002,
    name: 'QuarkChain Mainnet Shard 1',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39001/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/1',
  },
  {
    chainId: 100003,
    name: 'QuarkChain Mainnet Shard 2',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39002/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/2',
  },
  {
    chainId: 100004,
    name: 'QuarkChain Mainnet Shard 3',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39003/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/3',
  },
  {
    chainId: 100005,
    name: 'QuarkChain Mainnet Shard 4',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39004/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/4',
  },
  {
    chainId: 100006,
    name: 'QuarkChain Mainnet Shard 5',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39005/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/5',
  },
  {
    chainId: 100007,
    name: 'QuarkChain Mainnet Shard 6',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39006/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/6',
  },
  {
    chainId: 100008,
    name: 'QuarkChain Mainnet Shard 7',
    rpc: 'http://eth-jrpc.mainnet.quarkchain.io:39007/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://mainnet.quarkchain.io/7',
  },
  {
    chainId: 110000,
    name: 'QuarkChain Devnet Root',
    rpc: 'http://jrpc.devnet.quarkchain.io:38391/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 110001,
    name: 'QuarkChain Devnet Shard 0',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39900/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/0',
  },
  {
    chainId: 110002,
    name: 'QuarkChain Devnet Shard 1',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39901/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/1',
  },
  {
    chainId: 110003,
    name: 'QuarkChain Devnet Shard 2',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39902/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/2',
  },
  {
    chainId: 110004,
    name: 'QuarkChain Devnet Shard 3',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39903/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/3',
  },
  {
    chainId: 110005,
    name: 'QuarkChain Devnet Shard 4',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39904/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/4',
  },
  {
    chainId: 110006,
    name: 'QuarkChain Devnet Shard 5',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39905/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/5',
  },
  {
    chainId: 110007,
    name: 'QuarkChain Devnet Shard 6',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39906/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/6',
  },
  {
    chainId: 110008,
    name: 'QuarkChain Devnet Shard 7',
    rpc: 'http://eth-jrpc.devnet.quarkchain.io:39907/',
    nativeCurrency: {
      name: 'QKC',
      symbol: 'QKC',
      decimals: 18,
    },
    explorer: 'https://devnet.quarkchain.io/7',
  },
  {
    chainId: 200625,
    name: 'Akroma',
    rpc: 'https://remote.akroma.io',
    nativeCurrency: {
      name: 'Akroma Ether',
      symbol: 'AKA',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 246529,
    name: 'ARTIS sigma1',
    rpc: 'https://rpc.sigma1.artis.network',
    nativeCurrency: {
      name: 'ARTIS sigma1 Ether',
      symbol: 'ATS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 246785,
    name: 'ARTIS Testnet tau1',
    rpc: 'https://rpc.tau1.artis.network',
    nativeCurrency: {
      name: 'ARTIS tau1 Ether',
      symbol: 'tATS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 333888,
    name: 'Polis Testnet',
    rpc: 'https://sparta-rpc.polis.tech',
    nativeCurrency: {
      name: 'tPolis',
      symbol: 'tPOLIS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 333999,
    name: 'Polis Mainnet',
    rpc: 'https://rpc.polis.tech',
    nativeCurrency: {
      name: 'Polis',
      symbol: 'POLIS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 421611,
    name: 'Arbitrum Testnet Rinkeby',
    rpc: 'https://rinkeby.arbitrum.io/rpc',
    nativeCurrency: {
      name: 'Arbitrum Rinkeby Ether',
      symbol: 'ARETH',
      decimals: 18,
    },
    explorer: 'https://rinkeby-explorer.arbitrum.io',
  },
  {
    chainId: 1313114,
    name: 'Ether-1',
    rpc: 'https://rpc.ether1.org',
    nativeCurrency: {
      name: 'Ether-1 Ether',
      symbol: 'ETHO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1313500,
    name: 'Xerom',
    rpc: 'https://rpc.xerom.org',
    nativeCurrency: {
      name: 'Xerom Ether',
      symbol: 'XERO',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 7762959,
    name: 'Musicoin',
    rpc: 'https://mewapi.musicoin.tw',
    nativeCurrency: {
      name: 'Musicoin',
      symbol: 'MUSIC',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 13371337,
    name: 'PepChain Churchill',
    rpc: 'https://churchill-rpc.pepchain.io',
    nativeCurrency: {
      name: 'PepChain Churchill Ether',
      symbol: 'TPEP',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 18289463,
    name: 'IOLite',
    rpc: 'https://net.iolite.io',
    nativeCurrency: {
      name: 'IOLite Ether',
      symbol: 'ILT',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 20181205,
    name: 'quarkblockchain',
    rpc: 'https://hz.rpc.qkiscan.cn',
    nativeCurrency: {
      name: 'quarkblockchain Native Token',
      symbol: 'QKI',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 28945486,
    name: 'Auxilium Network Mainnet',
    rpc: 'https://rpc.auxilium.global',
    nativeCurrency: {
      name: 'Auxilium coin',
      symbol: 'AUX',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 35855456,
    name: 'Joys Digital Mainnet',
    rpc: 'https://node.joys.digital',
    nativeCurrency: {
      name: 'JOYS',
      symbol: 'JOYS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 61717561,
    name: 'Aquachain',
    rpc: 'https://c.onical.org',
    nativeCurrency: {
      name: 'Aquachain Ether',
      symbol: 'AQUA',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 99415706,
    name: 'Joys Digital TestNet',
    rpc: 'https://toys.joys.cash/',
    nativeCurrency: {
      name: 'TOYS',
      symbol: 'TOYS',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 311752642,
    name: 'OneLedger Mainnet',
    rpc: 'https://mainnet-rpc.oneledger.network',
    nativeCurrency: {
      name: 'OLT',
      symbol: 'OLT',
      decimals: 18,
    },
    explorer: 'https://mainnet-explorer.oneledger.network',
  },
  {
    chainId: 1122334455,
    name: 'IPOS Network',
    rpc: 'https://rpc.iposlab.com',
    nativeCurrency: {
      name: 'IPOS Network Ether',
      symbol: 'IPOS',
      decimals: 18,
    },
    explorer: '',
  },

  {
    chainId: 1313161555,
    name: 'Aurora TestNet',
    rpc: 'https://rpc.testnet.aurora.dev:8545',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'aETH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1313161556,
    name: 'Aurora BetaNet',
    rpc: 'https://rpc.betanet.aurora.dev:8545',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'aETH',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1666600000,
    name: 'Harmony Mainnet Shard 0',
    rpc: 'https://api.harmony.one',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: 'https://explorer.harmony.one',
  },
  {
    chainId: 1666600001,
    name: 'Harmony Mainnet Shard 1',
    rpc: 'https://s1.api.harmony.one',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1666600002,
    name: 'Harmony Mainnet Shard 2',
    rpc: 'https://s2.api.harmony.one',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1666600003,
    name: 'Harmony Mainnet Shard 3',
    rpc: 'https://s3.api.harmony.one',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1666700000,
    name: 'Harmony Testnet Shard 0',
    rpc: 'https://api.s0.b.hmny.io',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: 'https://explorer.pops.one',
  },
  {
    chainId: 1666700001,
    name: 'Harmony Testnet Shard 1',
    rpc: 'https://api.s1.b.hmny.io',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1666700002,
    name: 'Harmony Testnet Shard 2',
    rpc: 'https://api.s2.b.hmny.io',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 1666700003,
    name: 'Harmony Testnet Shard 3',
    rpc: 'https://api.s3.b.hmny.io',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'ONE',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 3125659152,
    name: 'Pirl',
    rpc: 'https://wallrpc.pirl.io',
    nativeCurrency: {
      name: 'Pirl Ether',
      symbol: 'PIRL',
      decimals: 18,
    },
    explorer: '',
  },
  {
    chainId: 4216137055,
    name: 'OneLedger Testnet Frankenstein',
    rpc: 'https://frankenstein-rpc.oneledger.network',
    nativeCurrency: {
      name: 'OLT',
      symbol: 'OLT',
      decimals: 18,
    },
    explorer: 'https://frankenstein-explorer.oneledger.network',
  },
  {
    name: 'Cronos Mainnet Beta',
    chain: 'CRO',
    rpc: 'https://evm-cronos.crypto.org',
    faucets: [],
    nativeCurrency: {
      name: 'Crypto.org Coin',
      symbol: 'CRO',
      decimals: 18,
    },
    infoURL: 'https://cronos.crypto.org',
    shortName: 'cro',
    chainId: 25,
    networkId: 25,
    explorers: [
      {
        name: 'Cronos Explorer',
        url: 'https://cronos.crypto.org/explorer',
        standard: 'none',
      },
    ],
  },
  {
    name: 'Aurora MainNet',
    chain: 'NEAR',
    rpc: 'https://mainnet.aurora.dev',
    faucets: [],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'aETH',
      decimals: 18,
    },
    infoURL: 'https://aurora.dev',
    shortName: 'aurora',
    chainId: 1313161554,
    networkId: 1313161554,
    explorers: [
      {
        name: 'explorer.aurora.dev',
        url: 'https://explorer.mainnet.aurora.dev',
        standard: 'EIP3091',
      },
    ],
  },
  {
    name: 'Moonbeam',
    chain: 'MOON',
    rpc: 'https://rpc.api.moonbeam.network',
    faucets: [],
    nativeCurrency: {
      name: 'Glimmer',
      symbol: 'GLMR',
      decimals: 18,
    },
    infoURL: 'https://moonbeam.network/networks/moonbeam/',
    shortName: 'mbeam',
    chainId: 1284,
    networkId: 1284,
    explorers: [
      {
        name: 'blockscout',
        url: 'https://blockscout.moonbeam.network',
        standard: 'none',
      },
      {
        name: 'moonscan',
        url: 'https://moonbeam.moonscan.io',
        standard: 'none',
      },
    ],
  },
  {
    name: 'Emerald Paratime Mainnet',
    chain: 'Emerald',
    icon: 'oasis',
    rpc: 'https://emerald.oasis.dev',
    faucets: [],
    nativeCurrency: {
      name: 'Emerald Rose',
      symbol: 'ROSE',
      decimals: 18,
    },
    infoURL: 'https://docs.oasis.dev/general/developer-resources/overview',
    shortName: 'oasis',
    chainId: 42262,
    networkId: 42262,
    explorers: [
      {
        name: 'Emerald Paratime Mainnet Explorer',
        url: 'https://explorer.emerald.oasis.dev',
        standard: 'EIP3091',
      },
    ],
  },
  {
    name: 'Evmos',
    chainId: 9001,
    shortName: 'evmos',
    networkId: 9001,
    nativeCurrency: {
      name: 'Evmos',
      symbol: 'EVMOS',
      decimals: 18,
    },
    rpc: 'https://eth.bd.evmos.org',
    faucets: [],
    infoURL: 'https://evmos.org',
  },
  {
    name: 'DogeChain',
    chainId: 2000,
    shortName: 'doge',
    networkId: 2000,
    nativeCurrency: {
      name: 'doge',
      symbol: 'doge',
      decimals: 18,
    },
    rpc: 'https://rpc01-sg.dogechain.dog',
    faucets: [],
    infoURL: '',
  },
  {
    name: 'Redlight',
    chainId: 2611,
    shortName: 'redlight',
    networkId: 2611,
    nativeCurrency: {
      name: 'REDLC',
      symbol: 'REDLC',
      decimals: 18,
    },
    rpc: 'https://dataseed2.redlightscan.finance/',
    faucets: [],
    infoURL: '',
  },
];
